#!/usr/bin/env bash

set -e

JD_DIRECTORY=~/.jdownloader
LOG_FILE=$JD_DIRECTORY/jdownloader.log
JAVA_OPTIONS="-Xmx512m"
NUMBER_OF_UPDATE_MIRRORS=3

download_updater() {
  RANDOM_NUMBER=$(dd if=/dev/urandom count=1 2>/dev/null | cksum | cut -f1 -d" ")
  MIRROR=http://update$(expr $RANDOM_NUMBER % $NUMBER_OF_UPDATE_MIRRORS).jdownloader.org/

  rm -f jdupdate.jar
  echo "$0: Download jdupdate.jar from $MIRROR." >> $LOG_FILE
  curl -vLO $MIRROR/jdupdate.jar 2>>$LOG_FILE || zenity --error --text \
    "The JDownloader updater could not be downloaded. \
    \nCheck your Internet connection and try again. \
    \nThe error log can be found in $LOG_FILE."

  rm -f jdupdate.jar.md5
  echo "$0: Download jdupdate.jar.md5 from $MIRROR." >> $LOG_FILE
  curl -vLO $MIRROR/jdupdate.jar.md5 2>>$LOG_FILE || zenity --error --text \
    "The JDownloader updater MD5 sum file could not be downloaded. \
    \nCheck your Internet connection and try again. \
    \nThe error log can be found in $LOG_FILE."

  ACTUAL_MD5SUM=$(md5sum jdupdate.jar | cut -f1 -d" ")
  TARGET_MD5SUM=$(cat jdupdate.jar.md5)
  [[ "$ACTUAL_MD5SUM" = "$TARGET_MD5SUM" ]] || zenity --warning --text \
    "The MD5 sum of the JDownloader updater mismatches. \
    \nEither there was a download error or one of the files \
    (downloader or md5 sum file) is not up-to-date. \
    \nThe log file can be found in $LOG_FILE."
}

# determine command line parameters
while getopts ':u' opt; do
  case $opt in
    u) update=1;;
  esac
done

# create JDownloader directory, if it is missing (e.g. first run)
[[ ! -d "$JD_DIRECTORY" ]] && mkdir -p "$JD_DIRECTORY"
cd "$JD_DIRECTORY"

# clear log
> $LOG_FILE

# download updater, if it is missing (e.g. first run)
if [[ ! -f jdupdate.jar ]]; then
  echo "$0: No installer/updater found in $JD_DIRECTORY." >> $LOG_FILE
  download_updater
fi

# start update if requested
if [[ "$update" = "1" ]]; then
  echo "$0: Starting updater by your request." >> $LOG_FILE
  exec java $JAVA_OPTIONS -jar jdupdate.jar
elif [[ -f JDownloader.jar ]]; then
  echo "$0: Starting JDownloader." >> $LOG_FILE
  exec java $JAVA_OPTIONS -jar JDownloader.jar $*
else
  # run updater, if JDownloader.jar does not exist
  echo "$0: No valid JDownloader.jar exist. Starting updater." >> $LOG_FILE
  exec java $JAVA_OPTIONS -jar jdupdate.jar
fi
